language: c++
sudo: required
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y  cmake libeigen3-dev
  - wget --no-check-certificate http://www.sfml-dev.org/files/SFML-2.3.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.bz2
  - tar -xzvf /tmp/sfml.tar.bz2
  - sudo cp -r SFML-2.3.2/* /usr/
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - libeigen3
    - libjpeg62-dev
    - libsndfile1-dev
    - libglew1.5
    - libglew1.5-dev
    - libfreetype6
    - libjpeg-turbo8
    - libjpeg8
    - libopenal-data
    - libopenal1
    - libxrandr2
    - libxrender1
    - libsoil1
    - libudev-dev
    - libxcb-randr-dev
    - libxcb-image-dev
script:
    - cmake .
    - make
