language: c++
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y  cmake libeigen3-dev
    - wget http://sfml-dev.org/download/sfml/2.2/SFML-2.2-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
    - tar -xjvf /tmp/sfml.tar.bz2
    - sudo cp -r SFML-2.1/* /usr/
    - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
script:
    - cmake .
    - make
